# User creation playbook
---
- name: Create user
  hosts: "{{ target }}"
  gather_facts: yes
  become: yes
  become_method: sudo
  become_user: root

  tasks:

    - name: Create user
      user:
        name: ansible
        createhome: yes
        state: present
        # password: "{{ mts1234 | password_hash('sha512') }}"
        password: $6$mysecretsalt$zd6jwPHMHoV9UiAFTzd.G8Hms3YlCNB9YBHtCWhRD2LRsIg5E5PGos8YOMnFHLdxYa/CcjeTmwB5qfnvVAvnG/
        update_password: on_create
    
    - name: Add user to sudoers
      copy:
        src: ../files/ansible.sudo
        dest: "/etc/sudoers.d/ansible"
        owner: root
        group: root
        mode: 0440
        validate: "visudo -csf %s"