---
- name: Update dnf & Install apche server on centos8
  hosts: "{{ target }}"
  gather_facts: true
  become: true
  become_method: sudo
  become_user: root

  tasks:

    - name: Ensure DNF cache is up to date
      dnf:
        update_cache: yes
    
    - name: Install Apache (httpd) on CentOS 8
      dnf:
        name: httpd
        state: present
    
    - name: Start Apache service
      service:
        name: httpd
        state: started
        enabled: yes
    
    - name: Allow HTTP traffic through the firewall
      firewalld:
        service: http
        permanent: yes
        state: enabled
    
    - name: Reload firewall to apply changes
      command: firewall-cmd --reload
    
    - name: Ensure Apache is running
      service:
        name: httpd
        state: started
        
    - name: Install PHP 7.4
      package:
        name: php
        state: present
    
    - name: Install MySQL server
      package:
        name: mysql-server
        state: present
    
    - name: Ensure MySQL service is running and enabled
      service:
        name: mysqld
        state: started
        enabled: yes  
        
    - name: Synchronize website template from Ansible controller to client server
      synchronize:
        src: ../files/lawfirm/
        dest: /var/www/html/
        recursive: yes
        mode: push
    
    - name: Create info.php page for the website
      copy: 
        content: "<?php phpinfo(); ?>"
        dest: /var/www/html/info.php
        mode: '0644'  
